// src/views/Repositories.vue
<template>
  <div>
    <el-card>
      <div v-if="loading" class="loading">
        <i class="el-icon-loading"></i>
        {{ $t("common.loading") }}
      </div>

      <div v-if="!loading">
        <el-table :data="repositories" style="width: 100%" height="calc(100vh - 200px)" stripe row-class-name="mono">
          <el-table-column fixed :label="$t('repositories.repository')" width="300">
            <template slot-scope="scope">
              <a :href="scope.row.repo" target="_blank" class="sans-serif">{{ scope.row.repo }}</a>
            </template>
          </el-table-column>
          <el-table-column prop="type" :label="$t('repositories.type')" width="150" sortable>
          </el-table-column>
          <el-table-column
            prop="vrpsTotal"
            :label="$t('repositories.vrpsTotal')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="vrpsUnsafe"
            :label="$t('repositories.vrpsUnsafe')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="vrpsLocallyFiltered"
            :label="$t('repositories.vrpsLocallyFiltered')"
            width="180"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="vrpsDuplicate"
            :label="$t('repositories.vrpsDuplicate')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="vrpsFinal"
            :label="$t('repositories.vrpsFinal')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="validPublicationPoints"
            :label="$t('repositories.validPublicationPoints')"
            width="200"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="rejectedPublicationPoints"
            :label="$t('repositories.rejectedPublicationPoints')"
            width="220"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="validManifests"
            :label="$t('repositories.validManifests')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="invalidManifests"
            :label="$t('repositories.invalidManifests')"
            width="180"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="staleManifests"
            :label="$t('repositories.staleManifests')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="missingManifests"
            :label="$t('repositories.missingManifests')"
            width="180"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="validCRLs"
            :label="$t('repositories.validCRLs')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="invalidCRLs"
            :label="$t('repositories.invalidCRLs')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="staleCRLs"
            :label="$t('repositories.staleCRLs')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="strayCRLs"
            :label="$t('repositories.strayCRLs')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="validCACerts"
            :label="$t('repositories.validCACerts')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="validEECerts"
            :label="$t('repositories.validEECerts')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="invalidCerts"
            :label="$t('repositories.invalidCerts')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="validROAs"
            :label="$t('repositories.validROAs')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="invalidROAs"
            :label="$t('repositories.invalidROAs')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="validGBRs"
            :label="$t('repositories.validGBRs')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="invalidGBRs"
            :label="$t('repositories.invalidGBRs')"
            width="150"
            sortable
          >
          </el-table-column>
          <el-table-column
            prop="otherObjects"
            :label="$t('repositories.otherObjects')"
            width="150"
            sortable
          >
          </el-table-column>
        </el-table>
      </div>
    </el-card>
  </div>
</template>

<script>
import APIService from "@/services/APIService.js";

export default {
  data() {
    return {
      loading: false,
      repositories: [],
    };
  },
  created() {
    this.loadStatus();
  },
  methods: {
    loadStatus() {
      this.loading = true;
      APIService.getStatus().then((response) => {
        this.status = response.data;
        this.loading = false;
        if (this.status && this.status.version) {
          this.$emit("update-version", this.status.version);
        }
        if (this.status.repositories) {
          let repos = [];
          Object.keys(this.status.repositories).forEach((k) => {
            repos.push({
              repo: k,
              ...this.status.repositories[k],
            });
          });
          this.repositories = repos;
        }
      });

      return false;
    },
  },
};
</script>

// src/components/Repositories.tsx
import React, { useContext, useState } from 'react';
import { t } from '../core/util';
import { Repository } from '../types';
import { StatusContext } from '../hooks/useStatus';

type RepositoryKey = keyof Repository;

const columns: RepositoryKey[] = [
  'repository',
  'type',
  'vrpsTotal',
  'vrpsUnsafe',
  'vrpsLocallyFiltered',
  'vrpsDuplicate',
  'vrpsFinal',
  'validPublicationPoints',
  'rejectedPublicationPoints',
  'validManifests',
  'invalidManifests',
  'staleManifests',
  'missingManifests',
  'validCRLs',
  'invalidCRLs',
  'staleCRLs',
  'strayCRLs',
  'validCACerts',
  'validEECerts',
  'invalidCerts',
  'validROAs',
  'invalidROAs',
  'validGBRs',
  'invalidGBRs',
  'otherObjects',
];

export default function Repositories() {
  const { status } = useContext(StatusContext);
  const [sort, setSort] = useState<RepositoryKey | null>(null);
  let values = Object.entries(status.repositories);

  if (sort) {
    values = values.sort((a, b) => {
      return ((b[1][sort] as number) || 0) - ((a[1][sort] as number) || 0);
    });
  }

  return (
    <div id="repositories" className="scroll-table">
      <div>
        <table>
          <thead>
            <tr>
              {columns.map((key) => (
                <th
                  key={key}
                  onClick={() => setSort(key)}
                  className={`${sort === key ? 'active' : ''}`}
                >
                  {t(`repositories.${key}`)}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {values.map(([key, repository]: [string, Repository]) => (
              <tr key={key}>
                <th scope="row" title={key}>
                  <a href={key} target="_blank" rel="noreferrer">
                    {key}
                  </a>
                </th>
                {columns.slice(1).map((key: RepositoryKey) => (
                  <td key={key}>
                    {(repository[key] || 0).toLocaleString('en')}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
